### ISSUE TITLE
fixing autolabel

### ISSUE THREAD

**Issue by mbraidy** [kartik-v/yii2-checkbox-x#12]
After last update, I started getting :
Setting unknown property: kartik\checkbox\CheckboxX::autoLabel

**Comment by kartik-v** [comment]
You do not have the latest updated version of the extension. 

Ensure your app `composer.json` has the right settings for the packages and versions.

Note that proper version dependencies have been incorporated in most Krajee extensions.

**Comment by mbraidy** [comment]
I have this in my composer.json

        "kartik-v/yii2-checkbox-x": "@dev",
and still it is not working
