### ISSUE TITLE
Zbigniew Szczęsny's post on http://demos.krajee.com/checkbox-x is an issue.

### ISSUE THREAD

**Issue by jsivakumaran** [kartik-v/yii2-checkbox-x#15]
Actually, there is a problem with this plugin. When using as ActiveForm enhancement like this:

echo $form->field($model, 'status')->widget(CheckboxX::classname(),
[
'initInputType' => CheckboxX::INPUT_CHECKBOX,
'autoLabel' => true,
'pluginOptions' => [
'threeState' => false,
],
])->label(false);

1) it is impossible to change checkbox state with clicking on the checkbox itself. It is only working while clicking on the label (please notice, the issue is not occuring while "threeState" option is set to "true").

2) Initial checkbox state is always "checked", regardless of the "status" value set in $model.

Actually, both issues can be solved by setting "initInputType" to "CheckboxX::INPUT_TEXT" but then the checkbox value sent while submitting is always "0" regardless checkbox state. It is possible to overcome this problem using event function:

'pluginEvents' => [
'change' => 'function(e){
var el = $(e.target);
if(el.val() == "0"){
el.attr("value", "0");
}else if(el.val() == "1"){
el.attr("value", "1");
}
}',
],

Only then you'll get properly working, two-state enhanced active checkbox. I hope this will help avoiding frustrations while using this plugin.

By the way, Kartik - is toggling checkbox state with clicking on its label a bug or a feature of the Checkbox-X as well as FormBuilder checkbox widget? Actually I think it is a bug rather than feature. In my humble opinion, only clicking on a checkbox itself should change its state.

Sincerely,
Ziggi

**Comment by kartik-v** [comment]
You need to read the [plugin docs and options](http://plugins.krajee.com/checkbox-x) correctly. 

For the use case above set the [enclosedLabel](http://plugins.krajee.com/checkbox-x#option-enclosedlabel) plugin property to `true` and it will work. NOTE THAT yii active field CHECKBOX renders checkbox enclosed within a label. So setting the following will work:

```php
echo $form->field($model, 'status')->widget(CheckboxX::classname(),
    [
        'initInputType' => CheckboxX::INPUT_CHECKBOX,
        'autoLabel' => true,
        'pluginOptions' => [
            'enclosedLabel' => true,
            'threeState' => false,
        ],
])->label(false);
```

**Comment by jsivakumaran** [comment]
Sorry about that.  I should have been more clear.  It's not the clicking label vs checkbox that is posing a problem for me but the fact that the default always seems to be checked even if the model underlying it is unchecked.

2) Initial checkbox state is always "checked", regardless of the "status" value set in $model.

For any update form the checkbox shows up as checked even if the 'status' is unchecked in the backend.

**Comment by kartik-v** [comment]
The above issue is resolved in [enhancement # 42 of the plugin](https://github.com/kartik-v/bootstrap-checkbox-x/issues/42).

**Comment by quemuel** [comment]
remove 'initInputType' => CheckboxX::INPUT_CHECKBOX
