### ISSUE TITLE
Bootstrap 4 Default

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-checkbox-x#16]
When using with Bootstrap V4+, check the box has no visual effect, because glyphicon is used as default and this is dropped from BS4. 

There's workaround solution as follows:
```
<?= $form->field($model, 'field1')->widget(CheckboxX::classname(), [
            'pluginOptions' =>[
                'iconChecked' => '<i class="fas fa-check"></i>',
            ],
        ]) ?>
```
However since I'm working on an existing project and it's quite a lot of work to update all fields. Is there a way this can be configured globally in the mean time? Have tried to follow [this example](https://stackoverflow.com/questions/20183622/how-do-i-set-a-default-configuration-for-gridview-in-yii2-without-the-widget-fac) but it's not working.

**Comment by kartik-v** [comment]
Will record an enhancement and resolve this. Thanks for the feedback,

**Comment by kartik-v** [comment]
Resolved you can check now (remember to set the `bsVersion` setting as described in the documentation in the [bootstrap info](http://localhost/demos/checkbox-x#bs-info) section).

**Comment by cluwong** [comment]
Working now. Thanks for the quick fix.
