### ISSUE TITLE
Default value when ['threeState' => false]

### ISSUE THREAD

**Issue by pavlinter** [kartik-v/yii2-checkbox-x#4]
When i create new item and don't touch Active field, CheckboxX show error 'Active cannot be blank.'
I offer:

<pre>
class CheckboxX extends InputWidget
{
    public function init()
    {
        ........
        if (isset($this->pluginOptions['threeState']) && $this->pluginOptions['threeState']) {
            echo $this->getInput('checkbox');
        } else {
            echo $this->getInput('textInput');
        }
    }
</pre>

OR set default value '0' through javascript

**Comment by nagyt234** [comment]
I'm using option 1 and 3 together.
Option 1: in model's rules:
 ```
    public function rules()
    {
        return [
            [['is_hidden'], 'boolean'],
            [['is_hidden'], 'required'],
            ....
```
Option 3: in model's controller:
```
    public function actionCreate()
    {
        $model = new ModelName();
        $model->loadDefaultValues();    # Not defaultValues() (!)
        ....
```
